# Generated by Django 5.2.1 on 2025-05-27 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facil_sys_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuloTreinamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ConteudoTreinamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('texto', 'Texto'), ('video', 'Vídeo'), ('pdf', 'PDF')], max_length=10)),
                ('titulo', models.CharField(max_length=255)),
                ('texto', models.TextField(blank=True, null=True)),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='treinamentos/')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conteudos', to='facil_sys_app.modulotreinamento')),
            ],
        ),
    ]
