# Generated by Django 5.2.1 on 2025-05-27 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facil_sys_app', '0002_modulotreinamento_conteudotreinamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Treinamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('texto', 'Texto'), ('video', 'Vídeo'), ('pdf', 'PDF')], max_length=10)),
                ('titulo', models.CharField(max_length=255)),
                ('conteudo', models.TextField(blank=True, null=True)),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='treinamentos/')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ConteudoTreinamento',
        ),
        migrations.DeleteModel(
            name='ModuloTreinamento',
        ),
    ]
