# Generated by Django 5.2.1 on 2025-05-27 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facil_sys_app', '0003_treinamento_delete_conteudotreinamento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treinamento',
            name='tipo',
        ),
    ]
