# Generated by Django 5.2.1 on 2025-05-28 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facil_sys_app', '0004_remove_treinamento_tipo'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConteudoTreinamentoPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('modulo', models.CharField(max_length=255)),
                ('titulo', models.CharField(max_length=255)),
                ('conteudo', models.TextField(blank=True)),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='treinamentos/')),
                ('tipo', models.CharField(choices=[('texto', 'Texto'), ('video', 'Vídeo'), ('pdf', 'PDF')], max_length=50)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
