# Generated by Django 5.2.1 on 2025-05-28 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facil_sys_app', '0005_conteudotreinamentopage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConteudoTreinamentoPage',
        ),
    ]
