# Generated by Django 5.2.1 on 2025-06-07 23:48

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facil_sys_app', '0006_delete_conteudotreinamentopage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treinamento',
            name='arquivo',
        ),
        migrations.AlterField(
            model_name='treinamento',
            name='conteudo',
            field=wagtail.fields.StreamField([('paragrafo', 0), ('imagem', 1), ('video', 2)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ul', 'ol']}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 2: ('wagtail.embeds.blocks.EmbedBlock', (), {})}, default=list),
        ),
        migrations.AlterField(
            model_name='treinamento',
            name='modulo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='treinamento',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
    ]
