# Generated by Django 5.2.1 on 2025-06-12 23:54

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facil_sys_app', '0007_remove_treinamento_arquivo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Convenios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('conteudo', wagtail.fields.StreamField([('paragrafo', 0), ('imagem', 1), ('video', 2)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ul', 'ol']}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 2: ('wagtail.embeds.blocks.EmbedBlock', (), {})}, default=list)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
